version: "3"

tasks:
  generate:
    cmds:
      - uv run generate_pages.py

  buildOnWindows:
    cmds:
      - cd static && ../tailwindcss.exe -i "tailwind.css" -o "style.css" --minify

  serveOnWindows:
    deps: [buildOnWindows]
    cmds:
      - echo "Starting server at http://localhost:8000"
      - cd static && python3 -m http.server 8000

  build:
    deps: [generate]
    cmds:
      - cd static && tailwindcss -i "tailwind.css" -o "style.css" --minify
    sources:
      - "**/*.html"
      - "static/tailwind.css"
    generates:
      - "static/style.css"

  watch:
    deps: [generate]
    cmds:
      - cd static && tailwindcss -i "tailwind.css" -o "style.css" --watch
    sources:
      - "**/*.html"
      - "static/tailwind.css"

  serve:
    deps: [build]
    cmds:
      - echo "Starting server at http://localhost:8000"
      - cd static && python3 -m http.server 8000

  windows:
    desc: (for windows) build and run the site locally

    deps:
      - buildOnWindows
    cmds:
      - task: serveOnWindows

  default:
    desc: (for linux/macos) build and run the site locally
    deps: [serve]
